server:
  port: 8080

spring:
  application:
    name: pedidoService

main:
  allow-bean-definition-overriding: true

data:
  mongodb:
    database: pedidoservice_db
    host: localhost  # Cambiado de "mongo_DB" a "localhost"
    port: 27017
