server:
  port: 8080

spring:
  application:
    name: Inventario

  data:
    mongodb:
      uri: mongodb://localhost:27017/inventario_db  # URI correcta para MongoDB

main:
  allow-bean-definition-overriding: true
